<script>
    $(document).ready(function() {
        $("#navigationBar li").removeClass("active");
        $("#navAbout").addClass("active");
    });
</script>

<section id="about" style="margin-top: 100px;">
    <div class="page-header">
        <h1>About</h1>
    </div>
    <div class="row">
        <div class="span10 text-justify">
            <p>
                Nowadays I work as a programmer at <a href="www.zonmadeira.pt/"></a> Zon Madeira. 
            </p>
            <p>
                I also worked as Research Assistant at M-ITI, where I finished my MSc. I worked on the <a href="http://www.m-iti.org/node/59"> ZON Service Engineering </a> project under Software Engineering Institute | Carnegie Mellon and the University of Hawaii, and I was responsible for developing a new MetaSketch a new soccer prototype.
            </p>
            <p>
                I live in Madeira and I have a BSc in Computer Science, also from University of Madeira. In my free time I enjoys a good book, play basketball and beach volleyball and also play video games.
            </p>
        </div>
        <div class="span1">
            <div class="well" style="width: 120px; ">
                <a href="/pdf/CV_EN_062013.pdf" target="_blank">
                    <img src="/images/CV.jpg" alt="curriculum vitae">
                </a>
            </div>
        </div>
    </div>
    <div class="page-header">
        <h1>Work Experience</h1>
    </div>
    <div class="row">
        <div class="span8">
            <p><i><b>Programmer</b></i> </p>
            <p>July 2012 - Present, ZON Madeira</p>
            <p>&nbsp;</p>
            <p><i><b>Research Assistant - ZON Service Engineering Project</b></i> </p>
            <p>August 2011 - June 2012, Madeira Interactive Technologies Institute</p>
            <p>&nbsp;</p>
            <p><i><b>Assistant professor - Computer architecture</b></i> </p>
            <p>April 2012 - May 2012, University of Madeira</p>
            <p>&nbsp;</p>
            <p><i><b>Monitor - Computer architecture</b></i> </p>
            <p>February 2011 - July 2011, University of Madeira</p>
        </div>
    </div>
</section>