<script>
    $(document).ready(function() {
        $("#navigationBar li").removeClass("active");
        $("#navContact").addClass("active");
    });
</script>
<section id="contact" style="margin-top: 100px;">
    <div class="page-header">
        <h1>Contact</h1>
    </div>
    <div class="row">
        <div class="span12">
            <p>
                <a href="mailto:juanjardim@gmail.com">
                    <img src="/images/gmail_16.png"  alt="My Email">
                </a>
                juanjardim(at)gmail.com
            </p>
            <p>
                <img src="/images/skype_16.png"  alt="My Skype alias">
                juan-jardim
            </p>
        </div>
    </div>
</section>