<div class="wrap" id="home">
 <div class="container">
 <div class="container content">
 <div class="row">
 <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 wow fadeInUp animated" data-wow-duration="2s">
 <h2>"Design is not just what it looks like and feels like.
 Design is how it works."</h2>
 <p class="pull-right">Steve Jobs</p>
 </div>
 <div class="col-lg-6 col-md-6 col-sm-5 hidden-xs wow fadeInRight animated" data-wow-duration="2s">
 <img class="img-responsive" src="/assets/images/responsive-icons.png" alt="responsive">
 </div></div></div></div></div>
<div class="row no-side-padding no-side-margin">
 <div class="container" id="journey">
 <ul class="timeline">
 <li>
 <div class="timeline-badge success"><i class="fa fa-thumbs-o-up"></i></div>
 <div class="timeline-panel animated wow fadeInLeft">
 <div class="timeline-heading">
 <div class="row">
 <div class="col-lg-3 col-md-3 col-sm-5 col-xs-6"><img class="img-circle img-responsive my-self" src="/images/myself.jpg" alt="Juan Jardim"></div>
 <div class="col-lg-9 col-md-9 col-sm-7 col-xs-6 no-side-padding">
 <h1 class="timeline-title" style="margin-top: 20px">Welcome</h1>
 </div></div></div>
 <div class="timeline-body">
 <p> Hi, my name is Juan Jardim and I am a software engenering working at the new NOS company, old ZON.</p>
 <p>First, I want to thank you for your visit and any feedback that you can give me in order to improve my skills.</p>
 <p>Secondly, I want you to know that in this site you will find information about my work, experiences and what I like in a professional level.</p>
 <p>Finally, I hope you have fun and enjoy this site.</p>
 </div></div></li>
 <li class="timeline-inverted">
 <div class="timeline-badge"><i class="fa fa-paper-plane-o"></i></div>
 <div class="timeline-panel scrollpoint animated wow fadeInRight">
 <div class="timeline-heading">
 <img class="img-responsive center-image" src="/assets/images/nos.png" alt="NOS">
 </div>
 <div class="timeline-body">
 <p>On October the 2nd, 2013 the fusion between ZON and Optimus was achieved and a new company were born. In May 2014 this company starts a new era as NOS where ours clients has a many advantages in terms of Television, Voice, Internet and Mobile.</p>
 <p>I started working as a programer, at Zon Madeira in 2012 until the present day. Now this company is called NOS Madeira. In this company I have been developing different skills in terms of Web programing and Web Design. Here, I learned and worked with:</p>
 <div class="row" style="margin-top: 20px">
 <div class="col-lg-4 col-md-4">
 <i class="fa fa-check-square-o"></i> HTML5/CSS3
 </div>
 <div class="col-lg-4 col-md-4">
 <i class="fa fa-check-square-o"></i> Ember.js
 </div>
 <div class="col-lg-4 col-md-4">
 <i class="fa fa-check-square-o"></i> Zend Framework
 </div></div></div></div></li>
 <li>
 <div class="timeline-badge danger"><i class="fa fa-briefcase"></i></div>
 <div class="timeline-panel scrollpoint animated wow fadeInLeft">
 <div class="timeline-heading">
 <img class="img-responsive center-image" src="/assets/images/UMa.png" alt="UMA" style="width: 50%;">
 </div>
 <div class="timeline-body">
 <p>Since 2011 I've been giving pratical lectures of the Computer Architecture course as a Guest Professor at University of Madeira. In this course, we propose three projects to the students:</p>
 <p>The first project is about building their own CPU in VHDL and then use the FPGAs to simulate a very simple program using this CPU.</p>
 <p>In the second project, the students have to resolve a problem using Assembly language. For example a ticket system for a movie theater.</p>
 <p>And in the third project, the students have to build a system, using electronics components such as leds, microcontrollers, etc. to solve a problem. Then they have to make a program in Assembly and C in order to achieve their goals.<br/>
 </p></div></div></li>
 <li class="timeline-inverted">
 <div class="timeline-badge info"><i class="fa fa-graduation-cap"></i></div>
 <div class="timeline-panel scrollpoint animated wow fadeInRight">
 <div class="timeline-heading">
 <img class="img-responsive center-image" src="/assets/images/M-ITI.png" alt="M-ITI">
 </div><div class="timeline-body">
 <p>At the end of 2011 I started My Thesis in the field of visualizations and Programing at MITI. The focus of my these was about how can we use visualization techniques in order to improve the knowledge about our model (UML, HAM, etc).</p>
 <p>After this, I started working at M-ITI as a Research Assistant in the Zon Service Engineering project, where I developed tools to supports models like UML and afterwards developing a proof concept of an application to support interactivity in a soccer game.</p>
 <p>The main idea of this App was to give the user the opportunity of going back in the game and see the best moments, or see only the goals that occurred in the game, among other cool things. The technologies used were: HTML5 and Jquery for the browser and television Application, for the backend: Java and REST, and Objective-C for the IPad App.</p>
 </div></div></li></ul></div></div>
<div class="row no-side-padding no-side-margin">
 <div class="container" id="experience">
 <h1 class="page-header">Experience</h1>
 <div class="row">
 <p>In the pas few year I've learning a lot of programing languages and framework such as:</p>
 </div>
 <div class="row">
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.0s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> HTML5 + CSS3</h4>
 <p>I've been learning HTML and CSS from the high school and at NOS Madeira I've been deepening and learning new concepts about these technologies.</p>
 </div></div>
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.1s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> Jascript & JQuery</h4>
 <p>I've started to work with JQuery and Javascript at college when my team elaborate a blog manager that we called UMa blog.</p>
 </div></div>
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.2s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> Zend Framework 1 &amp; 2</h4>
 <p>I started learning ZF1 at NOS Madeira, it was the first time that I used a framework like this one and recently I've been learning ZF2 for a new project.</p>
 </div></div>
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.3s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> Bootstrap</h4>
 <p>I also learned to work with this framework at NOS Madeira, because we needed an standardization for our internal layout of the tools that we are developing.</p>
 </div></div></div>
 <div class="row">
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.0s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> Ember</h4>
 <p>For several project, that I'm responsible for, We needed a MVC in the client side for better code organization, so I learned how to use Ember in order to achieve this, since the early stage of Ember.</p>
 </div></div>
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.1s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> Node</h4>
 <p>I learned Node because we needed to create a system that could update the clients with real time data, one way to do that is using a publish/subscribe approach.</p>
 </div></div>
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.2s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> JSON</h4>
 <p>Because I work with WebServices the data that some WS returned is in JSON format.</p>
 </div></div>
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.3s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> SOAP & REST</h4>
 <p>Most of the WebServices in php that we created uses SOAP technology but I had already worked with REST at M-ITI.</p>
 </div></div></div>
 <div class="row">
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.0s">
 <div class="skill">
 <h4> <i class="fa fa-check-square-o"></i> Mysql</h4>
 <p>SQL languages are important for almost any application on software. I started working with MySql at college and NOS Madeira. I have already worked with MSSQL and Oracle Databases.</p>
 </div></div>
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.1s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> Assembly</h4>
 <p>I learned Assembly at college and I lectured this programing language at Madeira University.</p>
 </div></div>
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.2s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> VHDL</h4>
 <p>This is another programing language that I learned at college and I lectured at Madeira University. </p>
 </div></div>
 <div class="col-lg-3 col-md-3 col-sm-6 wow fadeInDown animated" data-wow-delay="1.3s">
 <div class="skill">
 <h4><i class="fa fa-check-square-o"></i> WPF</h4>
 <p>I learned WPF in order to create a proof concept of my thesis about model visualization. </p>
 </div></div></div>
 <div class="row"><p>In the next years, I would learn:</p></div>
 <div class="row wow fadeInDown animated">
 <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
 <div class="skill-to-learn">
 <h4><i class="fa fa-check-square-o"></i> SASS/LESS</h4></div></div>
 <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
 <div class="skill-to-learn"><h4><i class="fa fa-check-square-o"></i> Angular</h4></div></div>
 <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6"><div class="skill-to-learn"><h4><i class="fa fa-check-square-o"></i> Ruby</h4></div> </div>
 <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6"><div class="skill-to-learn"><h4> <i class="fa fa-check-square-o"></i> Python</h4>
 </div></div></div></div></div>
<div class="row no-side-padding no-side-margin" style="margin-top: 20px">
 <div class="container" id="work"><h1 class="page-header">Work</h1>
 <div class="row">
 <div class="col-lg-4 col-md-4 col-sm-6 animated wow fadeIn">
 <div class="thumbnail">
 <a href="/index/portfolio/#terapias">
 <div class="img-container">
 <img class="img-responsive" src="/images/Terapias/index.jpg" alt="Terapias">
 <div class="portfolio-overlay">
 <div class="portfolio-badge"><i class="fa fa-search"></i></div>
 </div></div>
 <div class="caption">
 <h4>Terapias</h4>
 <p>I am currently working in this project and it would help the customers In Madeira Island that want a really great massage to find it.</p>
 </div></a></div></div>
 <div class="col-lg-4 col-md-4 col-sm-6 animated wow fadeIn">
 <div class="thumbnail">
 <a href="/index/portfolio/#cook">
 <div class="img-container">
 <img class="img-responsive" src="/images/Project1/indexThumb.png" alt="Project">
 <div class="portfolio-overlay">
 <div class="portfolio-badge"><i class="fa fa-search"></i></div>
 </div></div>
 <div class="caption">
 <h4>Cooks</h4>
 <p>I am really excited about this project. It involves food, recipes and users who want to share their own recipes. </p>
 </div>
 </a></div></div>
 <div class="col-lg-4 col-md-4 col-sm-6 animated wow fadeIn">
 <div class="thumbnail">
 <a href="/index/portfolio/#myWebsite">
 <div class="img-container">
 <img class="img-responsive" src="/images/MyWebsite/myWebsiteThumb.png" alt="My Web Page">
 <div class="portfolio-overlay">
 <div class="portfolio-badge"><i class="fa fa-search"></i></div></div></div>
 <div class="caption">
 <h4>Personal Web Page</h4>
 <p>This is my personal web page.</p>
 </div></a></div></div>
 <div class="col-lg-4 col-md-4 col-sm-6 animated wow fadeIn">
 <div class="thumbnail">
 <a href="/index/portfolio/#cesarWebsite">
 <div class="img-container">
 <img class="img-responsive" src="/images/CesarWebsite/indexThumb.png" alt="Cesar Pires Web Site">
 <div class="portfolio-overlay">
 <div class="portfolio-badge"><i class="fa fa-search"></i></div>
 </div></div>
 <div class="caption">
 <h4>César Pires - Advogado Website</h4>
 <p>This site was made with the goal of promoting César work as a lawyer.</p>
 </div></a></div></div>
 <div class="col-lg-4 col-md-4 col-sm-6 animated wow fadeIn">
 <div class="thumbnail">
 <a href="/index/portfolio/#meta">
 <div class="img-container">
 <img class="img-responsive" src="/images/Meta/Visualizer1.jpg" alt="Meta Visualizer">
 <div class="portfolio-overlay">
 <div class="portfolio-badge"><i class="fa fa-search"></i></div></div></div>
 <div class="caption">
 <h4>Meta Visualizer</h4>
 <p>Theses project that allow to the user load models, perform queries and view the result of queries.</p>
 </div></a></div></div>
 <div class="col-lg-4 col-md-4 col-sm-6 animated wow fadeIn">
 <div class="thumbnail">
 <a href="/index/portfolio/#autoChef">
 <div class="img-container">
 <img class="img-responsive" src="/images/autoChef/AutoChef.jpg" alt="Auto Chef">
 <div class="portfolio-overlay">
 <div class="portfolio-badge"><i class="fa fa-search"></i></div></div></div>
 <div class="caption">
 <h4>Auto Chef</h4>
 <p>IHC project for a vending machine, which uses "the latest nanotechnology" to produce gourmet dishes without human intervention. </p>
 </div></a></div></div></div></div>
 <div class="row testimonials-section no-side-padding no-side-margin" style="margin-top: 20px">
 <div class="container wow fadeInUp animated" id="testimunials">
 <h1 class="page-header">Testimonials</h1>
 <div>
 <div class="col-md-offset-2 col-md-8 col-sm-12">
 <div class="carousel slide" data-ride="carousel" id="quote-carousel" style="margin-top: 100px; margin-bottom: 100px">
 <ol class="carousel-indicators">
 <li data-target="#quote-carousel" data-slide-to="0" class=""></li>
 <li data-target="#quote-carousel" data-slide-to="1" class=""></li>
 <li data-target="#quote-carousel" data-slide-to="2" class="active"></li>
 </ol>
 <div class="carousel-inner">
 <div class="item">
 <blockquote>
 <div class="row">
 <div class="col-sm-3 text-center"><img class="img-circle" src="https://media.licdn.com/mpr/mpr/shrink_200_200/p/8/005/049/1dd/1f15964.jpg" alt="linkedin"></div>
 <div class="col-sm-9">
 <p>"Juan is a talented software engineer. In the period I have worked with him, he performed very well; always finished the work effectively and meanwhile helped many other team members solve complex problems. He learned quickly, and always be humble and kind. It is my pleasure to work with him."</p>
 <small>Ko-Hsun Huang - <a href="tw.linkedin.com/pub/ko-hsun-huang/44/392/929/pt" target="_blank">@linkedin</a></small>
 </div></div></blockquote></div>
 <div class="item"><blockquote><div class="row"><div class="col-sm-3 text-center">
 <img class="img-circle" src="https://media.licdn.com/mpr/mpr/shrink_200_200/p/4/005/048/2ab/02bd936.jpg" alt="linkedin">
 </div><div class="col-sm-9">
 <p>"Juan performs exceptionally in high stress and short deadline situations. He was an asset within the project due to his persistence and hard work within and outside the office. Juan is a valuable and reliable colleague that will overcome technical difficulties efficiently and professionally.."</p>
 <small>Clinton Jorge - <a href="pt.linkedin.com/in/clintonjorge/pt" target="_blank">@linkedin</a></small>
 </div></div></blockquote></div>
 <div class="item active">
 <blockquote>
 <div class="row">
 <div class="col-sm-3 text-center">
 <img class="img-circle" src="https://media.licdn.com/media/p/4/000/178/150/171d09e.jpg" alt="linkedin">
 </div>
 <div class="col-sm-9">
 <p>"Juan is a hardworking and skillful software engineer. I've seen him work diligently in different project areas, always rising to each different challenge. He is also a polite and friendly person."</p>
 <small>Jorge Grenha Teixeira - <a href="pt.linkedin.com/in/grenhateixeira/pt" target="_blank">@linkedin</a></small>
 </div></div></blockquote></div></div>
 <a data-slide="prev" href="#quote-carousel" class="left carousel-control visible-md visible-lg"><i class="fa fa-chevron-left"></i></a>
 <a data-slide="next" href="#quote-carousel" class="right carousel-control visible-md visible-lg"><i class="fa fa-chevron-right"></i></a>
 </div></div></div></div></div>
 <div class="row contacts-section no-side-padding no-side-margin">
 <div class="container wow flipInY animated">
 <div class="pre-footer">
 <div class="container" id="contact">
 <div class="row">
 <div class="col-sm-8 col-xs-12">
 <h3 class="hidden-xs">Leave a message</h3>
 <form id="feedbackForm" method="post" action="/index/contact"><fieldset>
 <div class="form-group"> <input type="text" class="form-control" placeholder="First Name" name="firstname" id="firstname"></div>
 <div class="form-group"><input type="text" class="form-control" placeholder="Last Name" name="lastname" id="lastname"></div>
 <div class="form-group"><input type="email" class="form-control" placeholder="Email" id="email" name="email"></div>
 <div class="form-group"><textarea class="form-control" placeholder="Message" id="message" name="message"></textarea></div>
 <button type="submit" class="btn btn-primary">Send message</button>
 </fieldset></form></div>
 <div class="col-md-4 col-sm-4 col-xs-12" style="text-align: center;">
 <div class="col-xs-12">
 <h3>My Contacts</h3>
 <address class="margin-bottom-20">
 Email: <a href="mailto:info@metronic.com">juanjardim(at)gmail.com</a><br>
 Skype: <a href="skype:juan-jardim">Juan Jardim</a>
 </address></div>
 <div class="col-xs-12"><h3>Curriculum Vitae</h3><a href="/pdf/CV_EN_072014.pdf" target="_blank"><img class="cv-img" src="/images/CV.jpg" alt="Juan Jardim - CV" >
 </a></div></div></div></div></div></div></div>