<script>
    $(document).ready(function() {
        $("#navigationBar li").removeClass("active");
        $("#navWork").addClass("active");
    });
</script>
<section id="autochef" style="margin-top: 100px;">
    <div class="page-header">
        <h1>Auto Chef</h1>
    </div>
    <div class="row">
        <div class="span12 text-justify">
            <h3>Project Description</h3>
            <p >
                In the course of human-computer interaction was proposed to the students a project interation design. To do this, the students passed throughout a series of phases. These phases are: study and discovery, brainstorming, analysis and storyboarding, prototyping and usability, evaluation and the final prototype, evaluation and presentation.
                <br/>
                <br/>
                The chosen project was "AutoChef". For this project was necessary to design an interface for a vending machine, which uses "the latest nanotechnology" to produce gourmet dishes without human intervation. The user can adjust the flavor of the dishes and select the menu without their allergies and just need to put a few coins.
                <br/>
                <br/>
                In terms of tasks, the task proposed was to request a steak with fries, rice and eggs, well past, paying with a 10&#8364; and receiving the change.
            </p>

            <h2>Technologies Used</h2>
            <p>
                The project was developed in Flash using <a href="http://en.wikipedia.org/wiki/ActionScript#ActionScript_3.0" target="_blank">ActionScript 3.0</a> and <a href="http://en.wikipedia.org/wiki/XML" target="_blank">XML</a>. The XML file content the products, ingredients stock, prices, etc. of the vending machine, enabling a very dynamic application. 
                <br/>
                <br/>
            </p>
        </div>
    </div>
    <section>
        <div id="autochefCarousel" class="carousel slide  thumbnail span8 offset2">
            <ol class="carousel-indicators">
                <li data-target="#autochefCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#autochefCarousel" data-slide-to="1" class=""></li>
                <li data-target="#autochefCarousel" data-slide-to="2" class=""></li>
                <li data-target="#autochefCarousel" data-slide-to="3" class=""></li>
                <li data-target="#autochefCarousel" data-slide-to="4" class=""></li>
                <li data-target="#autochefCarousel" data-slide-to="5" class=""></li>
                <li data-target="#autochefCarousel" data-slide-to="6" class=""></li>
                <li data-target="#autochefCarousel" data-slide-to="7" class=""></li>
                <li data-target="#autochefCarousel" data-slide-to="8" class=""></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img src="/images/AutoChef.jpg">
                        <div class="carousel-caption">
                            <h4>Main menu</h4>
                            <p>In this menu the user can select: Customize menu, Quick menu, Drink, Desserts.</p>
                        </div>
                </div>
                <div class="item">
                    <img src="/images/AutoChef2.jpg">
                        <div class="carousel-caption">
                            <h4>Menu to create the dish</h4>
                            <p>In this menu the user can select the igredients to create the dish</p>
                        </div>
                </div>
                <div class="item">
                    <img src="/images/AutoChef3.jpg">
                        <div class="carousel-caption">
                            <h4>Choice of beverage</h4>
                        </div>
                </div>
                <div class="item">
                    <img src="/images/AutoChef4.jpg">
                        <div class="carousel-caption">
                            <h4>Choice of dessert</h4>
                        </div>
                </div>
                <div class="item">
                    <img src="/images/AutoChef5.jpg">
                        <div class="carousel-caption">
                            <h4>Customization of the request</h4>
                        </div>
                </div>
                <div class="item">
                    <img src="/images/AutoChef6.jpg">
                        <div class="carousel-caption">
                            <h4>Allergies</h4>
                        </div>
                </div>
                <div class="item">
                    <img src="/images/AutoChef7.jpg">
                        <div class="carousel-caption">
                            <h4>Choice of dessert</h4>
                        </div>
                </div>
                <div class="item">
                    <img src="/images/AutoChef8.jpg">
                        <div class="carousel-caption">
                            <h4>Choice of dessert</h4>
                        </div>
                </div>
                <div class="item">
                    <img src="/images/AutoChef9.jpg">
                        <div class="carousel-caption">
                            <h4>Choice of dessert</h4>
                        </div>
                </div>
            </div>
            <a class="left carousel-control" href="#autochefCarousel" data-slide="prev">‹</a>
            <a class="right carousel-control" href="#autochefCarousel" data-slide="next">›</a>
        </div>
    </section>
</section>
