<script>
    $(document).ready(function() {
        $("#navigationBar li").removeClass("active");
        $("#navWork").addClass("active");
    });
</script>
<section id="herbal" style="margin-top: 100px;">
    <div class="page-header">
        <h1>Herbal Clinic</h1>
    </div>
    <div class="row">
        <div class="span12 text-justify">
            <h3>Project Description</h3>
            <p >
                In the course of database management system was proposed to the students a project about DBMS. This project involved the creation of the database that will store plants, medicines, recipes, etc. 
                <br/>
                <br/>
                The users can insert, consult and edit the informations that are part of the herbal clinic.
            </p>
            <h2>Technologies Used</h2>
            <p>
                The project was developed in <a href="http://en.wikipedia.org/wiki/PHP" target="_blank">PHP</a> using as databese the <a href="http://en.wikipedia.org/wiki/MySql" target="_blank">MySql DBMS</a>.
            </p>
        </div>
    </div>
    <section>
        <div id="autochefCarousel" class="carousel slide thumbnail span8 offset2">
            <ol class="carousel-indicators">
                <li data-target="#autochefCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#autochefCarousel" data-slide-to="1" class=""></li>
                <li data-target="#autochefCarousel" data-slide-to="2" class=""></li>
                <li data-target="#autochefCarousel" data-slide-to="3" class=""></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img src="/images/HC1.jpg">
                        <div class="carousel-caption">
                        </div>
                </div>
                <div class="item">
                    <img src="/images/HC2.jpg">
                        <div class="carousel-caption">
                        </div>
                </div>
                <div class="item">
                    <img src="/images/HC3.jpg">
                        <div class="carousel-caption">
                        </div>
                </div>
                <div class="item">
                    <img src="/images/HC4.jpg">
                        <div class="carousel-caption">
                        </div>
                </div>
            </div>
            <a class="left carousel-control" href="#autochefCarousel" data-slide="prev">‹</a>
            <a class="right carousel-control" href="#autochefCarousel" data-slide="next">›</a>
        </div>
    </section>
</section>
