<script>
    $(document).ready(function() {
        $("#navigationBar li").removeClass("active");
        $("#navWork").addClass("active");
    });
</script>

<section id="work" style="margin-top: 100px;">
    <div class="page-header">
        <h1>Publications</h1>
    </div>
    <div class="row">
        <div class="span10 text-justify">
            <p>
                Juan Manuel Jardim Mendes, Guilherme Gomes, Leonel Nóbrega. "The other side of models: visualization techniques for exploring models." <a href="http://inforum.org.pt/INForum2011" target="_blank">INForum</a>, 2011.
            </p>
        </div>
        <div class="span1">
            <div class="well" style="width: 120px; ">
                <a href="/pdf/Artigo.pdf" target="_blank">
                    <img src="/images/paper.jpg" alt="Paper" >
                </a>
            </div>
        </div>
    </div>
    <div class="page-header">
        <h1>Thesis</h1>
    </div>
    <div class="row">
        <div class="span10 text-justify">
            <p>
                Juan Manuel Jardim Mendes. "The other side of models: visualization techniques for exploring models." MSc Thesis, Madeira Interactive Technologies Institute, University of Madeira, 2012. Grade 18.
            </p>
        </div>
        <div class="span1">
            <div class="well" style="width: 120px; ">
                <a href="/pdf/Tese.pdf" target="_blank">
                    <img src="/images/thesis.jpg" alt="Thesis" >
                </a>
            </div>
        </div>
    </div>    
</section>