<script>
$(document).ready(function() {
   $("#navigationBar li").removeClass("active");
   $("#navWork").addClass("active");
   $('.scroller').slimScroll({
    height: '250px'
});
});
</script>
<section id="autochef" style="margin-top: 100px;">
	<div class="page-header">
		<h1>Node.js</h1>
	</div>
	<div class="row">
        <div class="span12 text-justify">
            <h3>Project Description</h3>
            <p>
            	Tweets in Real Time 
                <br/>
                <br/>
                The JavaScript community has intensively grow in the past few years and a lot of web applications now demand real time data. For that reason, it's important to know what kinds of technologies are and how use them to provide this kind of data. Node.js it's build with that in mind and also with the asynchronous of the request in order to provide a fluid experience in the web.
                <br/>
                <br/>
                The main goal in this project it's to use a webSocket client that will connect to a node.js server and will show to the client side the last tweets of a twitter account. 
            </p>

            <h2>Technologies Used</h2>
            <p>
                The server was build using <a href="http://en.wikipedia.org/wiki/Nodejs" target="_blank">Node.js</a> and the client side use <a href="http://en.wikipedia.org/wiki/Nodejs" target="_blank">Socket.IO</a>
                <br/>
                <br/>
            </p>
            <p>
                <strong>Note: </strong> This may be take some seconds to someone write a tweet.
            </p> 
        </div>
        <div class="span12" style="margin-bottom: 100px;">
            <legend>Tweets from @KITKAT</legend>
            <div class="tweetContainer scroller">
                <ul class="tweet" id="tweets">
                </ul>
            </div>
        </div>
    </div>
</section>

<script src="http://juanjardim-tweetnode.rhcloud.com/socket.io/socket.io.js"></script>
<script>
state = true;
var socket = io.connect('http://juanjardim-tweetnode.rhcloud.com/', {reconnect: false});
socket.on('tweet', function (data) {
    var tweet = '';
    tweet += state ? '<li class="in">' : '<li class="out">';
    tweet += '<img class="avatar img-responsive" alt="" src=' + data.avatar + '>';
    tweet += '<div class="message">';
    tweet += '<span class="name">' + data.name + '</span>';
    tweet += '<span class="datetime">' + data.dateTime + '</span>';
    tweet += '<span class="body">';
    tweet +=  data.content;
    tweet += '</span>';
    tweet += '</div>';
    tweet += '</li>';
    state = !state;
    $("#tweets").prepend(tweet);
});

socket.on('disconnect', function () {
    console.log("Server Disconnect");
    socket.disconnect();
});

socket.on('connection', function(data){
    console.log("message: " + data);
})

socket.on('error', function (reason){ 
    console.log('Unable to connect Socket.IO', reason); 
});
</script>
