<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Juan Jardim - Web Developer </title>
    <meta name="keywords" content="Juan Jardim, Web Developer computer science, software,  Juan Manuel Jardim Mendes" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Juan Manuel Jardim Mendes">
    <meta name="description" content="Hi, I'm a Web Developer working at Zon Madeira, which is one of the best companies in telecommunications in Portugal. Here, I've been learning and developing, for almost two years, Responsive Web applications and also giving support to the backend area.">
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/style.css">        
    <link rel="stylesheet" href="/jquery.bxslider/jquery.bxslider.css">
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
    <meta property="fb:admins" content="250479071724249"/>    
</head>
<body>
    <div class="header navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle btn navbar-btn" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/index">Juan Jardim</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="<?php echo $this->indexClass;?>">
                       <a href="/index">Home</a>
                   </li>
                   <li class="<?php echo $this->portfolioClass;?>">
                       <a href="/index/portfolio">Portfolio</a>
                   </li>
                   <li class="<?php echo $this->contactClass;?>">
                       <a href="/index/contact">Contact</a>
                   </li>

               </ul>                         
           </div>
       </div>
   </div>
   <div class="page-container">
       <?php echo $this->layout()->content ?>
   </div>
   <div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-8 col-xs-8">
                <p><span class="margin-right-10">2013 © Juan Jardim. All Rights Reserved.</span></p>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-4">
                <ul class="social-footer">
                    <li><a href="https://www.facebook.com/JuanManuelJardimMendes" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="https://plus.google.com/+JuanManuelJardimMendes" rel="author" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="http://pt.linkedin.com/pub/juan-manuel-jardim-mendes/3b/591/29b" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#" title="juan-jardim"><i class="fa fa-skype"></i></a></li>
                </ul>       
            </div>
        </div>
    </div>
</div>
<script src="/js/jquery-1.10.2.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/jquery.slimscroll.min.js"></script>
<script src="/jquery.bxslider/jquery.bxslider.min.js"></script>
<script src="/js/app.js"></script>
</body>
</html>
