<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> Juan Jardim </title>
        <meta name="keywords" content="Juan Jardim, computer science, software, web development, Juan Manuel Jardim Mendes" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="This is my web site">
        <meta name="author" content="Juan Manuel Jardim Mendes">
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="/js/bootstrap.min.js"></script>
    </head>
    <body class="preview">

        <div id="wrap">
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container" >
                        <a class="brand" href="/index">Juan Jardim</a>
                        <div class="nav-collapse">
                            <ul class="nav" id="navigationBar">
                                <li id="navHome" ><a href="/index">Home</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Work <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/work">Publications and Thesis</a></li>
                                        <li><a href="/work/metavisualizer">Meta Visualizer</a></li>
                                        <li><a href="/work/autochef">Auto Chef</a></li>  
                                        <li><a href="/work/herbalclinic">Herbal Clinic</a></li> 
                                    </ul>
                                </li>
                                <li id="navAbout"><a href="/index/about">About</a></li>
                                <li id="navContact"><a href="/index/contact">Contact</a></li>
                            </ul>
                            <ul class="nav pull-right">
                                <li class="divider-vertical"></li>
                                <li style="height: 32px;">
                                    <a href="http://pt.linkedin.com/pub/juan-manuel-jardim-mendes/3b/591/29b">
                                        <img style="margin-top: -7px;" src="/images/linkedin.png" alt="LinkedIn" />
                                    </a>
                                </li>
                                <li style="height: 32px;">
                                    <a href="https://www.facebook.com/JuanManuelJardimMendes">
                                        <img style="margin-top: -7px;" src="/images/facebook.png" alt="Facebook" />
                                    </a>
                                </li>
                                <li style="height: 32px;">
                                    <a href="https://plus.google.com/101213346722883639390">
                                        <img style="margin-top: -7px;" src="/images/google.png" alt="Google Plus" />
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <?php echo $this->layout()->content ?>
            </div>
            <div id="push"></div>

        </div>
        <footer id="footer" class="navbar navbar-fixed-bottom">
            <div class="container">
                <div class="pull-left" >
                    <a href="http://validator.w3.org/check?uri=referer" class="html5">
                        <img src="/images/html5.png" alt="HTML5">
                    </a>
                </div>
                <p class="pull-right"><a href="#">Back to top</a></p>
            </div>
        </footer>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-42383248-1', 'juanjardim.com');
            ga('send', 'pageview');

        </script>
    </body>
</html>
